import Head from 'next/head'
import '../styles/globals.css'
import Navbar from '../components/Navbar';

function MyApp({ Component, pageProps }) {
  return(
    <>
      <Head>
        <title>Space Infinity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
      <footer className={`footer`}>
        <a
          href="https://github.com/roman-developer/space-infinity"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by José María Román.
        </a>
      </footer>
    </>
  )
}

export default MyApp
