import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Space Infinity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Space Infinity
        </h1>
        <div className={styles.welcome_menu}>
          <div>Solar System</div>
          <div>Mars</div>
          <div>More</div>  
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/roman-developer/space-infinity"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by José María Román.
        </a>
      </footer>
    </div>
  )
}
